query GetInventario {
  inventarios {
    idInventario
    cantidad
    ubicacion
    codProducto
    idAlmacen
    codProductoNavigation{
      nombre
      imagen
    }
    idAlmacenNavigation{
      nombre
    }
      
  }
}
