query {
  ventas {
    idVenta
    fecha
    hora
    monto
    idClienteNavigation {
      nombre
      apellidoPaterno
      direccion
    }
    idEmpleadoNavigation {
      nombre
      apellidoPaterno
    }
    detalleVenta {
      cantidad
      descuento
      codProductoNavigation {
        nombre
        precioVenta
      }
    }
  }
}
