mutation ActualizarEmpleado($input: EmpleadoInput!) {
  empleado {
    actualizarEmpleado(input: $input) {
      idEmpleado
      nombre
      apellidoPaterno
      apellidoMaterno
      sueldo
      turno
      cargo
    }
  }
}
